parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: osppms
    database_user: root
    database_password: sandra
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 5b93f5dda2ab526b6e49cb3afd62aa40c6412e9d
    database_path: null
